
					<h1><?php echo $this->item->title; ?></h1>

					<?php echo $this->item->body; ?>

					<p class="faux-h3"><strong><a href="/_includes/pdf/cazlock-CV.pdf" rel="external">Download my Résumé</a></strong></p>

					<ul id="contact-links" class="clearfix">
						<li id="contact-link-twitter"><a href="http://twitter.com/caz_lock" rel="external"><span class="context">Twitter</span></a></li>
						<li id="contact-link-facebook"><a href="http://www.facebook.com/cazlock" rel="external"><span class="context">Facebook</span></a></li>
						<li id="contact-link-flickr"><a href="http://www.flickr.com/photos/cazlock/" rel="external"><span class="context">Flickr</span></a></li>
						<li id="contact-link-linkedin"><a href="http://uk.linkedin.com/in/cazlock" rel="external"><span class="context">Linkedin</span></a></li>
						<li id="contact-link-society6"><a href="http://www.society6.com/cazlock" rel="external"><span class="context">Society6</span></a></li>
						<?php /*<li id="contact-link-lastfm"><a href="http://www.last.fm/user/Caz_Lock" rel="external"><span class="context">Lastfm</span></a></li> */ ?>
					</ul>
