<h1>The Trash Can</h1>

<?php if($this->wasDeleted): ?>

	<?php echo $this->partial('_partials/_status/_success.phtml', array ('type' => 'delete')); ?>

<?php elseif($this->wasRestored): ?>

	<?php echo $this->partial('_partials/_status/_success.phtml', array ('type' => 'restore')); ?>

<?php endif; ?>

<div id="items">

	<?php 
		echo $this->paginationControl($this->items,
		                                    'Sliding',
		                                    '_partials/_pagination.phtml', array(
												'items' => $this->items
											)); 
	?>

	<?php if (0 < count ($this->items)): ?>
	
		<table>
			<thead>
				<tr class="ui-widget-header">	   
					<th scope="col">System ID</th>					   	
					<th scope="col">Content</th>
					<th scope="col">From</th>
					<th scope="col">Deleted on</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
		
		<tbody>
			
			<?php foreach ($this->items as $i => $item): ?>
			
					<tr id="item-<?php echo $this->escape($item['id']); ?>">
						<td>              
							<?php  echo $this->escape($item['id']); ?>	          
						</td>
						<td>						
							<?php 
								if (isset($item['comment_content'])) {
									echo $item['comment_content'];
								} 
								if (isset($item['idea_content'])) {
									echo $item['idea_content'];
								}
								if (isset($item['parameters'])) {
									echo $item['parameters'];
								}
								if (isset($item['category'])) {
									echo $item['category'];
								}
							?>						
						</td>
						<td>	
							<?php echo str_replace('Default_Model_', '', $this->escape($item['modelName'])); ?>	
						</td>
						<td>              
							<?php if (isset($item['last_modified_date'])) { echo $this->formatDbDate($this->escape($item['last_modified_date']), "dd/MM/yyyy H:m"); } ?>	          
						</td>
						<td>
							<ul class="icons">
								<li class="ui-state-default">
									<a title="Delete this item" href="<?php 
										echo $this->url(
											array(
												'module' => 'admin', 
												'controller' => 'trash',
												'action' => 'delete',
												'id' => $this->escape($item['id']), 
												'model' => $item['modelName']
											), 
										'default', 
										true);
										?>
									">
										<span class="ui-icon ui-icon-trash"></span>
									</a>
								</li>
								<li class="ui-state-default">
									<a title="Restore this item" href="<?php 
										echo $this->url(
											array(
												'module' => 'admin', 
												'controller' => 'trash',
												'action' => 'restore',
												'id' => $this->escape($item['id']), 
												'model' => $item['modelName']
											), 
										'default', 
										true);
										?>
									">
										<span class="ui-icon ui-icon-check"></span>
									</a>
								</li>
							</ul>
						</td>		
					</tr>
			<?php endforeach; ?>		
		</tbody>
	</table>
	
	<?php 
		echo $this->paginationControl($this->items,
		                                    'Sliding',
		                                    '_partials/_pagination.phtml', array(
												'items' => $this->items
											)); 
	?>
	
	
	<?php else: ?>	
		<div id="info" class="ui-state-highlight">
			<p>
				<span class="ui-icon ui-icon-info"></span>
				<strong>There is no Trash!</strong>
				Items can be moved to the trash by clicking the little bin icon.
			</p>
		</div>
	<?php endif; ?>
</div>